name: build-demo-app

on:
  workflow_call
    
env:
  app_name: SparkDemo
  swift_version: '5.9'
  xcode_path: "/Applications/Xcode_15.4.app"
  xcodebuild_sdk: -sdk iphonesimulator
  xcodebuild_derivedData: ".derivedData/"
  xcodebuild_destination: -destination 'platform=iOS Simulator,name=iPhone 15 pro,OS=17.5'

jobs:
  build-demo-app:
    name: Check if Pull Request Comment contains '/buildDemo'
    runs-on: macos-14
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/buildDemo') }}
    steps:
    - name: Set Swift Version
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ env.swift_version }}

    - name: Get swift version
      run: swift --version

    - name: Select Xcode
      run: sudo xcode-select -s ${{ env.xcode_path }}

    - name: Checkout Action
      uses: actions/checkout@v4

    - name: Clone the demo project from a specific branch
      env:
        PR_COMMENT: ${{ github.event.comment.body }}
      run: |
        SPARK_IOS_BRANCH=${PR_COMMENT#'/buildDemo'}
        SPARK_IOS_BRANCH=${SPARK_IOS_BRANCH// /}
        if [ -z $SPARK_IOS_BRANCH ];then
          SPARK_IOS_BRANCH=main
        fi
        echo "Branch to clone on spark-ios: $SPARK_IOS_BRANCH"
        git clone -b $SPARK_IOS_BRANCH https://github.com/adevinta/spark-ios
    - name: Run xcodegen
      uses: xavierLowmiller/xcodegen-action@1.2.2
      with:
        spec: spark-ios/project.yml
        version: '2.41.0'

    - name: Inject current component package
      run: |
        PACKAGE=${PWD##*/}
        cd spark-ios/.gitscript
        swift inject_repository_package.swift $PACKAGE

    - name: Build
      run: |
        cd spark-ios
        xcodebuild -scheme ${{ env.app_name }} -derivedDataPath ${{ env.xcodebuild_derivedData }} ${{ env.xcodebuild_sdk }} ${{ env.xcodebuild_destination }} -resultBundlePath ${{ env.app_name }}.xcresult build

    - name: Upload xcresult file
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: ${{ env.app_name }}-${{ github.run_number }}.xcresult
        path: ${{ env.app_name }}.xcresult
        retention-days: 15

    - name: Upload demo app file
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      if: ${{ success() }}
      with:
        name: SparkDemo.app
        path: |
          spark-ios/${{ env.xcodebuild_derivedData }}Build/Products/Debug-iphonesimulator/SparkDemo.app
        retention-days: 15

    - name: Add a comment with the artifact link on the pull request
      uses: actions/github-script@v7.0.1
      if: ${{ success() }}
      env:
        PR_NUMBER: ${{ github.event.issue.number }}
        PR_NOTES: |
          [SparkDemo.app](${{ steps.artifact-upload-step.outputs.artifact-url }}) is available.

          Process:
           1. Download the app with the link above.
           2. Download if needed the [Sparkans](https://github.com/adevinta/spark-ios-configuration/releases/latest) mac os app.
           3. Launch Sparkans, on the **Simulators** entry on the sidebar, select the simulator you want and add the SparkDemo.app file.
           4. Envoy ;)
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: process.env.PR_NUMBER,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: process.env.PR_NOTES
          })